---
Resources:
  ApiDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - Id: ApiGateway
          CustomOriginConfig:
            HTTPPort: '80'
            HTTPSPort: '443'
            OriginProtocolPolicy: https-only
            OriginSSLProtocols: [ "TLSv1.2" ]
          OriginPath: ''
          DomainName: 
            Fn::GetAtt: [ CustomDomainName, RegionalDomainName ]
        Enabled: true
        HttpVersion: http2
        Comment: cdn for api gateway
        Aliases:
          - domain.tld
        PriceClass: PriceClass_All
        DefaultCacheBehavior:
          Compress: true
          AllowedMethods:
          - DELETE
          - GET
          - HEAD
          - OPTIONS
          - PATCH
          - POST
          - PUT
          CachedMethods:
          - HEAD
          - GET
          ForwardedValues:
            QueryString: true
            Headers: []
            Cookies:
              Forward: all
          MinTTL: '0'
          DefaultTTL: '0'
          TargetOriginId: ApiGateway
          ViewerProtocolPolicy: redirect-to-https
        CustomErrorResponses: []
        ViewerCertificate:
          AcmCertificateArn: arn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Logging:
          IncludeCookies: 'false'
          Bucket: ''
          Prefix: ''
        WebACLId: ''
  CustomDomainName:
    Type: 'AWS::ApiGatewayV2::DomainName'
    Properties:
      DomainName: ''
      DomainNameConfigurations:
        - CertificateArn: ''
          EndpointType: REGIONAL
          SecurityPolicy: TLS_1_2
  ApiMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties: 
      ApiId: 
        Ref: HttpApi
      DomainName: ''
      Stage:
        Ref: HttpApiStage

Outputs:
  ApiDistribution:
    Value:
      Fn::GetAtt: [ ApiDistribution, DomainName ]
